# Generated by Django 2.0.3 on 2018-04-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app06', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Article',
        ),
    ]
