# Generated by Django 2.0.3 on 2018-04-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app06', '0002_auto_20180427_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/', verbose_name='封面图'),
        ),
    ]
