# Generated by Django 2.0.3 on 2018-04-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nick_name',
            field=models.CharField(default='', max_length=20, verbose_name='分类别名'),
            preserve_default=False,
        ),
    ]
